version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: ankane/pgvector:latest
    container_name: threatmodel-postgres
    environment:
      POSTGRES_USER: threatmodel
      POSTGRES_PASSWORD: ${DB_PASSWORD:-threatmodel123}
      POSTGRES_DB: threatmodel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/architecture/database-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U threatmodel"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: threatmodel-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: threatmodel-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: threatmodel-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: threatmodel-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-threatmodel}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbitmq123}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Auth Service
  auth-service:
    build:
      context: ./backend/services/auth
      dockerfile: Dockerfile
    container_name: threatmodel-auth
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://threatmodel:${DB_PASSWORD:-threatmodel123}@postgres:5432/threatmodel_db
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-here}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your-refresh-secret-here}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"

  # Core Service
  core-service:
    build:
      context: ./backend/services/core
      dockerfile: Dockerfile
    container_name: threatmodel-core
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: threatmodel_db
      DB_USER: threatmodel
      DB_PASSWORD: ${DB_PASSWORD:-threatmodel123}
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-threatmodel}:${RABBITMQ_PASSWORD:-rabbitmq123}@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3002:3002"

  # AI Service (Node.js)
  ai-service:
    build:
      context: ./backend/services/ai
      dockerfile: Dockerfile
    container_name: threatmodel-ai
    environment:
      NODE_ENV: development
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: threatmodel_db
      DB_USER: threatmodel
      DB_PASSWORD: ${DB_PASSWORD:-threatmodel123}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3003:3003"

  # Diagram Service
  diagram-service:
    build:
      context: ./backend/services/diagram
      dockerfile: Dockerfile
    container_name: threatmodel-diagram
    environment:
      NODE_ENV: development
      PORT: 3004
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: threatmodel_db
      DB_USER: threatmodel
      DB_PASSWORD: ${DB_PASSWORD:-threatmodel123}
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3004:3004"

  # Report Service
  report-service:
    build:
      context: ./backend/services/reporting
      dockerfile: Dockerfile
    container_name: threatmodel-report
    environment:
      NODE_ENV: development
      PORT: 3005
      DATABASE_URL: postgresql://threatmodel:${DB_PASSWORD:-threatmodel123}@postgres:5432/threatmodel_db
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      REPORT_OUTPUT_DIR: /tmp/reports
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "3005:3005"

  # API Gateway
  api-gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    container_name: threatmodel-gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      AUTH_SERVICE_URL: http://auth-service:3001
      CORE_SERVICE_URL: http://core-service:3002
      AI_SERVICE_URL: http://ai-service:3003
      DIAGRAM_SERVICE_URL: http://diagram-service:3004
      REPORT_SERVICE_URL: http://report-service:3005
    depends_on:
      - auth-service
      - core-service
      - diagram-service
      - report-service
    ports:
      - "3000:3000"

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: threatmodel-frontend
    environment:
      API_GATEWAY_URL: http://api-gateway:3000
      ENVIRONMENT: production
    depends_on:
      - api-gateway
    ports:
      - "3006:3006"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Adminer (Database UI)
  adminer:
    image: adminer
    container_name: threatmodel-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # Grafana (Monitoring)
  grafana:
    image: grafana/grafana:latest
    container_name: threatmodel-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin123}
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3007:3000"

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: threatmodel-prometheus
    volumes:
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  minio_data:
  rabbitmq_data:
  ai_models:
  grafana_data:
  prometheus_data:

networks:
  default:
    name: threatmodel-network