global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@threatmodel.company.com'
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: critical-alerts
  - match:
      severity: warning
    receiver: warning-alerts

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://notification-service:3009/api/notifications/events'
    send_resolved: true
    http_config:
      bearer_token: 'your-webhook-token'
    title: 'Threat Modeling Platform Alert'
    text: |
      {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: 'security-team@company.com'
    subject: 'CRITICAL: Threat Modeling Platform Alert'
    body: |
      Critical alert triggered in Threat Modeling Platform:
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      Time: {{ .StartsAt }}
      {{ end }}
  
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#security-alerts'
    title: 'CRITICAL: Threat Modeling Platform'
    text: |
      {{ range .Alerts }}
      :rotating_light: *{{ .Annotations.summary }}*
      
      *Description:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
      *Service:* {{ .Labels.service }}
      *Time:* {{ .StartsAt }}
      {{ end }}
  
  webhook_configs:
  - url: 'http://notification-service:3009/api/notifications/events'
    send_resolved: true
    http_config:
      bearer_token: 'your-webhook-token'

- name: 'warning-alerts'
  email_configs:
  - to: 'devops-team@company.com'
    subject: 'WARNING: Threat Modeling Platform Alert'
    body: |
      Warning alert triggered in Threat Modeling Platform:
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.service }}
      Time: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']