global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Threat Modeling Platform Services
  - job_name: 'threatmodel-core'
    static_configs:
      - targets: ['core-service:3002']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'threatmodel-notification'
    static_configs:
      - targets: ['notification-service:3009']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'threatmodel-integration'
    static_configs:
      - targets: ['integration-service:3008']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'threatmodel-tmac'
    static_configs:
      - targets: ['tmac-service:3010']
    metrics_path: /metrics
    scrape_interval: 30s

  # Application health endpoints
  - job_name: 'threatmodel-health'
    static_configs:
      - targets: ['auth-service:3001', 'ai-service:3003', 'diagram-service:3004', 'report-service:3005', 'api-gateway:3000']
    metrics_path: /health
    scrape_interval: 60s

  # Infrastructure Services
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s