name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Lint and Format Check
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install dependencies (Auth Service)
        run: |
          cd services/auth-service
          npm ci
          
      - name: Install dependencies (AI/ML Service)
        run: |
          cd services/ai-ml-service
          npm ci
          
      - name: Lint Auth Service
        run: |
          cd services/auth-service
          npm run lint
          
      - name: Lint AI/ML Service
        run: |
          cd services/ai-ml-service
          npm run lint
          
      - name: Type Check Auth Service
        run: |
          cd services/auth-service
          npm run type-check
          
      - name: Type Check AI/ML Service
        run: |
          cd services/ai-ml-service
          npm run type-check

  # Unit Tests
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    
    strategy:
      matrix:
        service: [auth-service, ai-ml-service, user-service, project-service, threat-engine]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd services/${{ matrix.service }}
          npm ci
          
      - name: Run unit tests
        run: |
          cd services/${{ matrix.service }}
          npm test -- --coverage --watchAll=false
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: services/${{ matrix.service }}/coverage/lcov.info
          flags: ${{ matrix.service }}

  # Integration Tests
  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test-unit
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: threat_modeling_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Install dependencies (All Services)
        run: |
          for service in auth-service ai-ml-service user-service project-service; do
            cd services/$service
            npm ci
            cd ../..
          done
          
      - name: Run database migrations
        run: |
          cd infrastructure/database
          chmod +x run-migrations.sh
          POSTGRES_URL="postgresql://test_user:test_password@localhost:5432/threat_modeling_test" ./run-migrations.sh
          
      - name: Run integration tests
        env:
          DATABASE_URL: postgresql://test_user:test_password@localhost:5432/threat_modeling_test
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test
        run: |
          cd services/ai-ml-service
          npm run test:integration

  # E2E Tests
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: test-integration
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          
      - name: Start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
          
      - name: Wait for services to be ready
        run: |
          timeout 300 bash -c 'until curl -f http://localhost:3001/health; do sleep 5; done'
          timeout 300 bash -c 'until curl -f http://localhost:3002/health; do sleep 5; done'
          
      - name: Install test dependencies
        run: |
          cd services/ai-ml-service
          npm ci
          
      - name: Run E2E tests
        run: |
          cd services/ai-ml-service
          npm run test:e2e
          
      - name: Stop services
        if: always()
        run: |
          docker-compose -f docker-compose.yml down

  # Security Scan
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          
      - name: Run npm audit
        run: |
          for service in services/*/; do
            if [ -f "$service/package.json" ]; then
              echo "Auditing $service"
              cd "$service"
              npm audit --audit-level=moderate
              cd ../..
            fi
          done

  # Build and Push Docker Images
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [test-unit, security]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    strategy:
      matrix:
        service: [auth-service, ai-ml-service, user-service, project-service, threat-engine, report-service, notification-service, file-service, search-service, integration-service]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Deploy (placeholder for deployment steps)
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Add your deployment scripts here
          # kubectl apply -f k8s/staging/
          # helm upgrade --install threat-modeling ./helm-chart --namespace staging
          
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Add your production deployment scripts here
          # kubectl apply -f k8s/production/
          # helm upgrade --install threat-modeling ./helm-chart --namespace production