# Stale Issues and PR Management
# Runs on self-hosted runners: 192.168.1.16

name: 🧹 Stale Issues & PRs

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  stale:
    name: 🧹 Mark Stale Issues & PRs
    runs-on: [self-hosted, linux, docker]
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 🧹 Stale Action
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs within 7 days.
            Thank you for your contributions!
          stale-pr-message: |
            This PR has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs within 7 days.
            Thank you for your contributions!
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-stale: 30
          days-before-close: 7
          delete-branch: true
